from pydantic import BaseModel, Field


class SaveScanRequest(BaseModel):
    object_name: str = Field(...,
                             description="The original object scanned, e.g., Jeepney")
    chosen_lens: str = Field(...,
                             description="The strand they picked: STEM, ABM, HUMSS, TVL")
    ai_explanation: str = Field(...,
                                description="The teaser text generated by Gemini")
    xp_awarded: int = Field(
        default=10, description="Gamification points to award")
    image_url: str | None = Field(
        default=None, description="Optional URL if they uploaded a photo")


class SaveScanResponse(BaseModel):
    status: str
    message: str
    scan_id: str
